[build]
  command = "CI= npm run build"
  publish = "./dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = "200"
  force = true

[dev]
  functions = "netlify/functions"
  port = 8888

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"